version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: luscalone
          password: hunter00zZ  # context / project UI env-var reference
    steps:
      - checkout
      - run: ./mvn package
